### ISSUE TITLE
Error: Cannot find module '/../cli'

### ISSUE THREAD

**Issue by paolooo** [mikesmullin/borg#2]
I've got error after borg installation. I think it's looking for `.cli.coffee` file.

```
➜  borg  node -v
v0.10.35
➜  borg  npm -v
1.4.28
➜  borg  npm install borg -g
-
> borg@0.0.7 preinstall /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg
> npm install coffee-script -g

/Users/paowee/.nvm/v0.10.35/bin/coffee -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/bin/coffee
/Users/paowee/.nvm/v0.10.35/bin/cake -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/bin/cake
coffee-script@1.8.0 /Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script
└── mkdirp@0.3.5
/Users/paowee/.nvm/v0.10.35/bin/borg -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/bin/borg
borg@0.0.7 /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg
├── async2@0.1.9
├── lodash@2.4.1
├── sugar@1.4.1
└── ssh2@0.2.25 (streamsearch@0.1.2, asn1@0.1.11)
➜  borg  borg help
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
Error: Cannot find module '/../cli'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/paowee/Workspace/borg/.cli.coffee:1:1)
  at Object.<anonymous> (/Users/paowee/Workspace/borg/.cli.coffee:1:1)
  at Module._compile (module.js:456:26)
```

:)

**Comment by sbimikesmullin** [comment]
i was aware of this happening in borg <0.0.7. it looks like you have the latest version. 

The problem lines are here:
https://github.com/mikesmullin/borg/blob/master/bin/borg#L20-L21

my bash trick must not be working. Which OS and version are you on? Which shell do you use--bash?

**Comment by sbimikesmullin** [comment]
ah i see the problem now in your backtrace. the `readlink` command isn't available. i didn't realize this wasn't in all distros. thinking of an alternative

**Comment by sbimikesmullin** [comment]
@paolooo ok i committed a fix. see if it works for you now. do:
```bash
npm uninstall borg -g
npm install borg -g
```

**Comment by paolooo** [comment]
Perfect! It works now. I'm using OSx Yosemite v10.10.1
