### ISSUE TITLE
Error: Cannot find module './package.json'

### ISSUE THREAD

**Issue by paolooo** [mikesmullin/borg#3]
After I successfully installed `npm install borg -g`. I got the following error when I run `borg version` as well as `borg init Devops`. The error is  `Error: Cannot find module './package.json'`.

> OSx v10.10.1

```
➜  borg  borg version
zsh: command not found: borg
➜  borg  npm -v
1.4.28
➜  borg  node -v
v0.10.35
➜  borg  npm install borg -g
-
> borg@0.0.8 preinstall /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg
> npm install coffee-script node-inspector -g

/Users/paowee/.nvm/v0.10.35/bin/coffee -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/bin/coffee
/Users/paowee/.nvm/v0.10.35/bin/cake -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/bin/cake

> ws@0.4.32 install /Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> v8-debug@0.3.3 install /Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v11-darwin-x64/debug.node" is installed via remote

> v8-profiler@5.2.2 install /Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.2/node-v11-darwin-x64/profiler.node" is installed via remote
/Users/paowee/.nvm/v0.10.35/bin/node-inspector -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/bin/inspector.js
/Users/paowee/.nvm/v0.10.35/bin/node-debug -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector/bin/node-debug.js
coffee-script@1.8.0 /Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script
└── mkdirp@0.3.5

node-inspector@0.8.3 /Users/paowee/.nvm/v0.10.35/lib/node_modules/node-inspector
├── opener@1.4.0
├── which@1.0.8
├── async@0.9.0
├── semver@3.0.1
├── yargs@1.3.3
├── debug@1.0.4 (ms@0.6.2)
├── strong-data-uri@0.1.1 (truncate@1.0.4)
├── rc@0.5.5 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.3.2, minimist@0.0.10)
├── serve-favicon@2.2.0 (fresh@0.2.4, ms@0.7.0, parseurl@1.3.0, etag@1.5.1)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── ws@0.4.32 (tinycolor@0.0.1, options@0.0.6, commander@2.1.0, nan@1.0.0)
├── express@4.11.1 (merge-descriptors@0.0.2, utils-merge@1.0.0, methods@1.1.1, fresh@0.2.4, cookie@0.1.2, escape-html@1.0.1, range-parser@1.0.2, cookie-signature@1.0.5, finalhandler@0.3.3, vary@1.0.0, med
ia-typer@0.3.0, parseurl@1.3.0, serve-static@1.8.1, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.0, qs@2.3.3, debug@2.1.1, etag@1.5.1, on-finished@2.2.0, proxy-addr@1.0.5, send@0.11.1, type-i
s@1.5.5, accepts@1.2.2)
├── v8-debug@0.3.3 (nan@1.2.0)
└── v8-profiler@5.2.2 (nan@1.2.0)
/Users/paowee/.nvm/v0.10.35/bin/borg -> /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/bin/borg
borg@0.0.8 /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg
├── lodash@2.4.1
├── sugar@1.4.1
└── ssh2@0.3.6 (streamsearch@0.1.2, asn1@0.2.1, readable-stream@1.0.27-1)
➜  borg  borg version
Error: Cannot find module './package.json'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/cli.coffee:181:11)
  at Object.<anonymous> (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/cli.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/paowee/Workspace/borg/.cli.coffee:1:1)
  at Object.<anonymous> (/Users/paowee/Workspace/borg/.cli.coffee:1:1)
  at Module._compile (module.js:456:26)
```

**Comment by mikesmullin** [comment]
investigating

**Comment by mikesmullin** [comment]
ok try now.

**Comment by mikesmullin** [comment]
thanks for helping me test this on OS/X! :)

**Comment by paolooo** [comment]
You're welcome. I'm #1 fan of your works. :) Currently reinstalling  borg...

**Comment by paolooo** [comment]
This is fixed. Thanks :)
