### ISSUE TITLE
Error on Windows 7

### ISSUE THREAD

**Issue by paolooo** [mikesmullin/borg#5]
I'm using Windows 7. During installation I've encountered an error (See [screenshot](http://screencast.com/t/hp58SACp1p1x) ), and uname error, see the full logs below.

```bash
D:\
$ mkdir borg

D:\
$ cd borg

D:\borg
$ node -v
v0.10.35

D:\borg
$ npm -v
1.4.28

D:\borg
$ borg
'borg' is not recognized as an internal or external command,
operable program or batch file.

D:\borg
$ npm install borg -g
-
> borg@0.0.11 preinstall C:\Users\Nino\.nvmw\v0.10.35\node_modules\borg
> npm install coffee-script node-inspector -g

C:\Users\Nino\.nvmw\v0.10.35\coffee -> C:\Users\Nino\.nvmw\v0.10.35\node_modules\coffee-script\bin\coffee
C:\Users\Nino\.nvmw\v0.10.35\cake -> C:\Users\Nino\.nvmw\v0.10.35\node_modules\coffee-script\bin\cake
\


> ws@0.4.32 install C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\ws
$ node "C:\Users\Nino\.nvmw\v0.10.35\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\ws\build\bufferutil.vcproj' was not found or not a valid project file. [C:\Us
ers\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\ws\build\binding.sln]
VCBUILD : error : project file 'C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\ws\build\validation.vcproj' was not found or not a valid project file. [C:\Us
ers\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\ws\build\binding.sln]
\


> v8-profiler@5.2.3 install C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.3\node-v11-win32-x64\profiler.node" is installed via r
emote

> v8-debug@0.3.5 install C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.3.5\node-v11-win32-x64\debug.node" is installed via remote
C:\Users\Nino\.nvmw\v0.10.35\node-debug -> C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\bin\node-debug.js
C:\Users\Nino\.nvmw\v0.10.35\node-inspector -> C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector\bin\inspector.js
coffee-script@1.9.0 C:\Users\Nino\.nvmw\v0.10.35\node_modules\coffee-script

node-inspector@0.8.3 C:\Users\Nino\.nvmw\v0.10.35\node_modules\node-inspector
├── opener@1.4.0
├── which@1.0.8
├── async@0.9.0
├── semver@3.0.1
├── debug@1.0.4 (ms@0.6.2)
├── yargs@1.3.3
├── strong-data-uri@0.1.1 (truncate@1.0.4)
├── rc@0.5.5 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.3.3, minimist@0.0.10)
├── serve-favicon@2.2.0 (fresh@0.2.4, ms@0.7.0, parseurl@1.3.0, etag@1.5.1)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── ws@0.4.32 (tinycolor@0.0.1, options@0.0.6, commander@2.1.0, nan@1.0.0)
├── express@4.11.2 (merge-descriptors@0.0.2, fresh@0.2.4, escape-html@1.0.1, cookie@0.1.2, methods@1.1.1, utils-merge@1.0.0, cookie-signature@1.0.5, range-parser@1.0.2, finalhandle
r@0.3.3, media-typer@0.3.0, parseurl@1.3.0, vary@1.0.0, serve-static@1.8.1, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.0, qs@2.3.3, debug@2.1.1, etag@1.5.1, on-finis
hed@2.2.0, send@0.11.1, proxy-addr@1.0.6, type-is@1.5.7, accepts@1.2.4)
├── v8-profiler@5.2.3 (nan@1.5.3, node-pre-gyp@0.6.3)
└── v8-debug@0.3.5 (nan@1.6.2)
C:\Users\Nino\.nvmw\v0.10.35\borg -> C:\Users\Nino\.nvmw\v0.10.35\node_modules\borg\bin\borg
borg@0.0.11 C:\Users\Nino\.nvmw\v0.10.35\node_modules\borg
├── async2@0.1.9
├── sugar@1.4.1
├── ssh2@0.4.4 (readable-stream@1.0.33, ssh2-streams@0.0.6)
└── lodash@3.2.0

D:\borg
$ borg -v
      0 [main] uname 18884 open_stackdumpfile: Dumping stack trace to uname.exe.stackdump
Error: UNKNOWN, unknown error 'C:\Users\Nino\.nvmw\v0.10.35\node_modules\borg\bin\borg'
  at Object.fs.readlinkSync (fs.js:707:18)
  at Object.<anonymous> (.:8:88)
  at Object.<anonymous> (.:12:4)
  at Module._compile (module.js:456:26)

      0 [main] uname 19968 open_stackdumpfile: Dumping stack trace to uname.exe.stackdump
      0 [main] rm 20328 open_stackdumpfile: Dumping stack trace to rm.exe.stackdump

D:\borg
$
```

**Comment by mikesmullin** [comment]
ah yes i will list this on the readme. there will be no windows support :(

**Comment by sbimikesmullin** [comment]
as an update, you can run borg from within Cygwin using the mintty.exe bash console it provides.

**Comment by sbimikesmullin** [comment]
@paolooo yep got it working 100% on my Windows 8 Surface Pro 3 with Cygwin now.
updated readme to indicate windows support now.
